### ISSUE TITLE
High-level design

### ISSUE THREAD

**Issue by ixjlyons** [ucdrascal/axopy#1]
Just outlining some of the concepts for thinking about what AxoPy provides.

The concept so far is that there are a couple nested pipelines. In the inner layer, there are **tasks** which implement the workflow of a set of experimental trials. The task is set up as an event-driven network of signals and slots (in Qt speak) so that the API can essentially consist of connecting up basic elements.

Surrounding these task pipelines is a single **experiment** pipeline, which contains multiple tasks and ensures they have access to global data like the subject information, data storage, and I/O devices.

Some remaining questions:

* Does it make sense to make input/output devices persistent, or should these be created and destroyed at the task level? I can imagine an experiment with a task requiring a device which other tasks don't use, but tasks can just selectively activate the devices required. It could be wasteful to disconnect/reconnect to some kinds of devices.
* Should the task system be *completely* event-driven? I think in some cases it might be cumbersome to wire up every possible event in a task as a signal/slot. For example, a task could have a `cleanup` method that the user can fill in with code instead of forcing every operation to conform to the event-driven style.
* Can tasks be installed into the experiment in a way that allows them to be run more than once? It's pretty common to run a task several times, perhaps with a slightly different configuration. In some cases, it might make sense to create them as separate tasks, but in most cases I can think of, it's easier to allow for restarting a task. It *may* work to simply specify that a task repeats some block of trials and waits for a button press to start the next block. I'd rather not force that approach, though.
* It would be cool to keep the task/experiment API decoupled from a specific GUI toolkit. Does it make sense to support this as transparently as, say, matplotlib? That is, the user can specify that they want to use a specific backend but their code doesn't change. Another somewhat less complicated example I'm familiar with is [pyusb](https://github.com/walac/pyusb/).

**Comment by sixpearls** [comment]
Use a class definition approach to specifying experiments. The lowest level elements are ``Block``s and ``Stream``s, which are atomic units of accessing, generating, processing, and outputting data. The distinction is ``Block``s persist for only a trial (i.e., a specific filter or condition generator) while a ``Stream`` may persist longer, including the duration of experiment run-time.  ``Task``s are collections of ``Block``s with access to ``Stream``s, a specification for data flow between them, and a trial (``Trial``?) iteration manager. ``Experiment`` is a collection of ``Task``s and ``Stream``s, a way of passing data between ``Task``s (always via ``Stream``s?) and a specification for ``Task`` prerequisites and/or ordering.

At any level, may use specific classes that are coupled with a particular back end, (e.g., for sending and receiving signals, GUI, file io, etc) but as much as possible decouple this core experimental design framework from the other issues. Ideally, the use of classes coupled with a particular back-end can be deferred until the experimenter is implementing the experiment.

A potentially important part of decoupling will be a good options-with-defaults method including inheritance hierarchy to specify back-ends appropriately.

**Comment by sixpearls** [comment]
Perhaps this is a separate issue, but what is a good syntax for defining the trial manager?

Something similar to cycler might work. Ideally, the Task specification would be generic and potentially re-usable. So perhaps it only specifies which properties can be varied (to create specific trial conditions). Then when the experiment is implemented it specifies the actual conditions and how to iterate through them. 

Along with block specification, need to include end-of-trial triggers.

**Comment by ixjlyons** [comment]
I think most of this has settled into a pretty stable state.
