### ISSUE TITLE
Backend system

### ISSUE THREAD

**Issue by ixjlyons** [ucdrascal/axopy#3]
I'm currently thinking there are 2 types of backends that will need to be specified for an experiment:

- Hardware device I/O (e.g. thread, QThread, IPC with separate process) and storage (e.g. HDF5, MySQL, file system hierarchy) -- these are both persistent streams
- GUI (e.g. PyQt, pyglet)

Hardware and storage can be explicitly specified by instantiating the actual classes to use for these persistent streams. The UI backend can be specified at the experiment level. Tasks themselves can be built agnostic to any backend, and they'd ideally work on any of them.

An experiment might look something like:

```python
class CustomTask(BaseTask, InputTaskMixin):
    """Custom task implementation, not caring about backend."""
    ...

if __name__ == '__main__':
    experiment = Experiment(input_device=QThreadDevice(...), storage=HDF5Storage(...),
                            tasks=[CustomTask()], backend='qt')
    experiment.run()
```

The `Experiment` would then set up each task with the correct backend.

In a Qt-backed experiment, the way tasks are started could be by pressing a "start" button. In a pyglet-backed version, a key-press could start the tasks. The key could be specified through a `backend_kwargs` dict in `Experiment`, for example.

**Comment by sixpearls** [comment]
Here are a few slightly disorganized thoughts:

We need a way of deferring back-end support for tasks. This will probably be nice for organizing AxoPy but will also help with development. For example, a particular experiment may be the first to implement support for pyglets on particular tasks. It would be nice to be able to pin that experiment to a version of AxoPy without pyglets support and keep pyglets implementation in the experiment. Then at a later date, the tasks could be brought into AxoPy if they are general enough.

I don't know if the "plumbing" aspect of different blocks is inherently tied to the GUI back end. Perhaps this is actually something like the control-loop and/or display backend, with GUI being slightly different. For example, using pyglets to tightly control timing for a TAC task but using QT modal dialogues to select users, etc in prerequisite tasks.

I had originally been thinking ``Experiment`` classes would need to be pretty customizable, with a different sub-class for each experiment. But I think the way you've laid it out here makes more sense with generally one class or maybe one per GUI back-end or something. 

I was also thinking a hierarchy of option inheritance might be needed, but it's actually probably better without. We may be able to assume the ``Experiment`` has specific options and ``Task`` can inspect if needed, but the ``Task`` will use the backends consistent with the ``Experiment`` (and experiment). For users following the pattern you've laid out, mixing and matching back-ends, etc, should be unnecessary so it's probably fine.

**Comment by ixjlyons** [comment]
> For example, a particular experiment may be the first to implement support for pyglets on particular tasks. It would be nice to be able to pin that experiment to a version of AxoPy without pyglets support and keep pyglets implementation in the experiment. Then at a later date, the tasks could be brought into AxoPy if they are general enough.

Good point, didn't think about that. I can see this being done by writing a custom `PygletExperiment` class and then merging it in later by adding it as one of the possible options for the `backend` arg in `Experiment` once it's ready. This doesn't really add much except making it possible/easy to have default backends. Maybe it's better to just have specific experiment classes exposed (`QtExperiment`, `PygletExperiment`) and the user can select from them.

> I don't know if the "plumbing" aspect of different blocks is inherently tied to the GUI back end. Perhaps this is actually something like the control-loop and/or display backend, with GUI being slightly different. For example, using pyglets to tightly control timing for a TAC task but using QT modal dialogues to select users, etc in prerequisite tasks.

I'll have to take another look at psychopy's implementation of the dialogs. I suppose as long as the Qt event loop is created and destroyed along with the dialog, there isn't an issue. If we want to allow for a mixture of graphical backends, some more thought is required. I suppose doing participant selection with pure OpenGL (i.e. without a widgets system) would be a pain.

**Comment by ixjlyons** [comment]
I'm starting to second-guess the idea of supporting different graphical backends. I've had a quick look through [pyglet's programming guide](https://pyglet.readthedocs.io/en/latest/programming_guide/index.html) and it is an event-driven windowing toolkit much like Qt or any other. I'm still not totally clear on what psychopy does in all, but it seems to be a fairly complicated wrapper around the timing and event system to enforce accuracy. I'm actually not sure pyglet is crucial to its operation. It may have been a wise choice (it's probably more performant than other windowing toolkits and provides fairly direct integration with OpenGL [though Qt has that too]), but I'd be interested to ask the psychopy developers if it could have been implemented with any other GUI toolkit.

**Comment by ixjlyons** [comment]
Went ahead and asked: https://discourse.psychopy.org/t/could-psychopy-have-been-implemented-with-something-other-than-pyglet/1831

**Comment by sixpearls** [comment]
Awesome, thanks! Actually if psycho/pyglet are event driven, that makes me want to de-couple (not necessarily support) from the GUI toolkit even more. I'm not sure where the insertion point is to carefully control the timing, but I'm guessing taking it at the toolkit/backend level would be sufficient. It does suggest that the messaging/plumbing/etc can be tied directly to the backend though, which is helpful. 

This also suggests, as long as there are the right access points, we can just focus on the QT implementation for everything. But having the access points is probably good practice and shouldn't add too much overhead to development, so is probably worth doing.

**Comment by sixpearls** [comment]
The answer didn't seem particular helpful. I'm guessing the key to psychopy's timing is using the best timer API (Windows Query Performance Counter on windows and ``timer.timer`` or ``timeit.default_timer``, per psychopy/clock.py) and taking advantage of OpenGL features for tracking actual frames (psychopy/visual/window.py i.e., ``getActualFrameRate``). They also seem to judiciously turn off eventhandlers and switch between high- and low-precision timers.

Since our timing will have much more issue from synchronizing the display with the actual physical IO than anything else, you're probably right we can just ditch all other back ends. It might good to think about how to manage our timing and synchronize QT i/o with the physical i/o, but the default precision is likely sufficient and not worth trying to sort out.

**Comment by ixjlyons** [comment]
Yeah that was a bit underwhelming, I mean [Qt has hardware accelerated OpenGL support](https://doc.qt.io/qt-5/qtgui-index.html#opengl-and-opengl-es-integration). It's still not clear to me if pyglet is providing some fundamental flexibility to allow for accurate and precise timing or if Qt's event loop just has too much heft to guarantee it.

Anyway, I think this issue is resolved. For the persistent streams, the user can instantiate the specific implementations and as long as they have a standard interface, the `Experiment` and `Task` don't care.

**Comment by sixpearls** [comment]
I think they are breaking the pyglet event loop and drawing specific frames at specific rates for their highest precision timing. If you checkout the ``psychopy.clock.wait()``, it takes over the event loop and only (optionally) buffers key presses. 

But yes, I think that's the right design for AxoPy
