### ISSUE TITLE
Should emitters be called transmitters instead?

### ISSUE THREAD

**Issue by ixjlyons** [ucdrascal/axopy#8]
Let's play the analogy game: emitters are to detectors as transmitters are to receivers?

[Wikipedia's take from an information theoretic standpoint (my favorite standpoint):](https://en.wikipedia.org/wiki/Channel_capacity#Formal_definition)

![wikipedia's take](https://upload.wikimedia.org/wikipedia/commons/4/48/Comm_Channel.svg)

**Comment by sixpearls** [comment]
Based purely on # of characters, I would go with emitter and detector.. The method on the transmitter would probably also have to be transmit, rather than "emit."

But it's pretty silly so I say go with whatever analogy makes you happiest.

**Comment by ixjlyons** [comment]
closed by 6a465f8
